version: '3.9'

services:
  mongo:
    image: mongo:8.0
    container_name: test_project_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: test

volumes:
  mongo_data:
